const paths = [
  "/",
  "/404",
  "/_error: /500",
  "/about",
  "/blog",
  "/blog-detail-1",
  "/blog-detail-2",
  "/blog-detail-3",
  "/standard-blog",
  "/destination",
  "/destination-detail",
  "/destination-two",
  "/home-2",
  "/team",
  "/team-detail",
  "/tour",
  "/tour-detail",
  "/tour-detail-2",
  "/tour-detail-3",
  "/tour-grid",
  "/tour-list",
  "/contact",
  "/faq",
  "/forgot-password",
  "/gallery",
  "/gallery-masonry",
  "/hotels",
  "/hotels-detail",
  "/login",
  "/portfolio",
  "/register",
  "/sitemap",
  "/testimonial",
];

export default paths;
